### PR TITLE
quality: Fix some warnings

### PR DESCRIPTION
**Pull request by Elv13**
There is still many, many more, but at least this covers most of
Qt Clazy level 1 and some of the auto-fixit from level2.

Also disables `-Werror`. Werror should be a local `CXXFLAGS`/`CFLAGS`, not a project one. This break, among other things:

 * on each compiler updates
 * when the continuous integration system is configured to log *new* warnings when `-Weverything` (Clang) is enabled
 * when using a false positive prone linter, such as `clazy`

### CODE REVIEW

**Comment by callaa** [comment]
There's a bug in the commit. In `color_palette.cpp`, `QHash<QString,QString>` is changed to `QHash<QString,QStringRef>`. However, the QString object referenced by the QStringRef will be deleted on the next iteration of the loop.

**Comment by Elv13** [comment]
But wont the hash be long gone by then and the string "re-referenced" when calling `setName()`

**Comment by callaa** [comment]
I'm not sure what you mean. When `setName(properties[QStringLiteral("name")].toString())` is called, the returned QStringRef instance will point to memory freed earlier on line 216. QStringRef does not increment a string's reference count and so is only valid when the string it is referencing still exists.

**Comment by Elv13** [comment]
Right, I will report a bug to Clazy about the false positive. They list this one as 100% safe and false positive free. I force pushed a fix

**Comment by mbasaglia** [comment]
I believe this would break Qt 4 support, right?
It isn't an issue, but I'll have to keep in mind to remove the Qt4 checks if this is the case.

**Comment by Elv13** [comment]
I don't mind using a fork either. I guess merging this would cause more issues than it fixes. Shall I close this? The only reason this exists is to lower the warning count in my CI. Other than that, it is 0.1% faster, but who cares.

**Comment by mbasaglia** [comment]
Nah, it's fine. I'll have to check that everything still works for me though which might take a couple of days.

**Comment by mbasaglia** [comment]
Looks good to me

**Pull request merged**
